### PR TITLE
Fix: typos

### PR DESCRIPTION
**Pull request by omahs**
Fix: typos

### CODE REVIEW

**Comment by gabsn** [comment]
Thx @omahs!

**Comment by gabsn** [comment]
Please go to app.onlydust.xyz to collect your payment!

**Comment by omahs** [comment]
Ohhh that's sweet, I added my 0x 🚀

**Comment by omahs** [comment]
@gabsn Could you add me to the Telegram group for Only Dust? It seems that the Discord is inactive. https://t.me/omahs_tg

**Pull request merged**
